# External plugins
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
plugins:
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-feed

exclude:
  - "/vendor/"

# Site settings
title: Random Thoughts on Coding
subtitle: "A technical blog on whatever comes to mind"
email: bbejeck@gmail.com
name: Bill Bejeck
description: >
  Personal blog for the musing/rambling of Bill Bejeck
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl:
url: "https://bbejeck.github.io/" # the base hostname & protocol for your site
cover: "/assets/glacier_smaller.png"
logo: "/assets/favicon.png"

# Build settings
markdown: kramdown
inter_post_navigation: true
highlightjs_theme: "rainbow"

# Pagination Settings
# https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#site-configuration
pagination:
  enabled: true
  per_page: 5
  permalink: "/page/:num/"
  sort_reverse: true

jekyll-archives:
  enabled: 'all'
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

# Disqus comments
# disqus_shortname: bbejeck

# Google analytics
ga_tracking_id: "UA-16422585-1"


# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@bbejeck"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:
  - name: Twitter
    icon: twitter
    username: bbejeck
    url: https://twitter.com/bbejeck
    desc: Follow me on Twitter
    share: true

  - name: GitHub
    icon: github
    username: bbejeck
    url: https://github.com/bbejeck
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: bbejeck
    url: https://www.linkedin.com/in/bbejeck/
    desc: Connect with me on LinkedIn
    share: true

